name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # Retrieve the Z3 archive for the platform we're on.
    - name: Z3 windows
      if: startsWith(matrix.os, 'windows')
      shell: powershell
      run: |
        Invoke-WebRequest -Uri https://github.com/Z3Prover/z3/releases/download/z3-4.8.12/z3-4.8.12-x64-win.zip -OutFile z3-windows.zip
        Expand-Archive -Path z3-windows.zip -DestinationPath .
        echo "z3-windows/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Z3 ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.12/z3-4.8.12-x64-glibc-2.31.zip
        unzip z3-4.8.12-x64-glibc-2.31.zip
        echo `pwd`/z3-4.8.12-x64-glibc-2.31/bin >> $GITHUB_PATH
    - name: Z3 macos
      if: startsWith(matrix.os, 'macos')
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.12/z3-4.8.12-x64-osx-10.15.7.zip
        unzip z3-4.8.12-x64-osx-10.15.7.zip
        echo `pwd`/z3-4.8.12-x64-osx-10.15.7/bin >> $GITHUB_PATH

    - name: Z3 check help
      run: z3 -h

    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Documentation check
      run: cargo doc
    - name: Run tests
      run: cargo test --verbose -- --skip cvc4 --skip yices_2
